INSERT INTO vocabulary_items
  (deck_id, word, phonetic, part_of_speech, definition_en, definition_vi, example_sentence, example_sentence_vi, order_in_deck)
VALUES
  (1, 'apple', NULL, 'noun', 'A round fruit that is often red or green.', 'Quả táo, thường có màu đỏ hoặc xanh.', 'I eat an apple after lunch.', 'Tôi ăn một quả táo sau bữa trưa.', 101),
  (1, 'bread', NULL, 'noun', 'A basic food made from flour and water.', 'Bánh mì, món ăn làm từ bột mì và nước.', 'She buys fresh bread every morning.', 'Cô ấy mua bánh mì mới mỗi sáng.', 102),
  (1, 'milk', NULL, 'noun', 'A white drink from cows or plants.', 'Sữa, đồ uống màu trắng từ bò hoặc thực vật.', 'The child drinks milk before bed.', 'Đứa trẻ uống sữa trước khi ngủ.', 103),
  (1, 'coffee', NULL, 'noun', 'A hot drink made from roasted beans.', 'Cà phê, đồ uống làm từ hạt rang.', 'He orders coffee at the cafe.', 'Anh ấy gọi cà phê ở quán.', 104),
  (1, 'tea', NULL, 'noun', 'A drink made by putting leaves in hot water.', 'Trà, đồ uống pha từ lá trong nước nóng.', 'My grandmother likes green tea.', 'Bà tôi thích trà xanh.', 105),
  (1, 'rice', NULL, 'noun', 'Small white or brown grains eaten as food.', 'Cơm hoặc gạo, hạt nhỏ dùng làm thức ăn.', 'We have rice with dinner.', 'Chúng tôi ăn cơm vào bữa tối.', 106),
  (1, 'chicken', NULL, 'noun', 'A bird kept for meat and eggs.', 'Gà, loài gia cầm dùng lấy thịt và trứng.', 'Chicken soup is warm and simple.', 'Súp gà ấm và đơn giản.', 107),
  (1, 'egg', NULL, 'noun', 'An oval food from a bird.', 'Trứng, thực phẩm hình bầu dục từ gia cầm.', 'I cook an egg for breakfast.', 'Tôi nấu một quả trứng cho bữa sáng.', 108),
  (1, 'spoon', NULL, 'noun', 'A tool used for eating soup or soft food.', 'Cái thìa, dụng cụ để ăn súp hoặc đồ mềm.', 'Please give me a spoon.', 'Vui lòng đưa tôi một cái thìa.', 109),
  (1, 'plate', NULL, 'noun', 'A flat dish used for food.', 'Cái đĩa, vật phẳng dùng để đựng thức ăn.', 'Put the cake on the plate.', 'Đặt bánh lên đĩa.', 110),
  (1, 'chair', NULL, 'noun', 'A seat for one person.', 'Cái ghế, chỗ ngồi cho một người.', 'The chair is near the window.', 'Cái ghế ở gần cửa sổ.', 111),
  (1, 'table', NULL, 'noun', 'A piece of furniture with a flat top.', 'Cái bàn, đồ nội thất có mặt phẳng.', 'The keys are on the table.', 'Chìa khóa ở trên bàn.', 112),
  (1, 'window', NULL, 'noun', 'An opening in a wall with glass.', 'Cửa sổ, ô mở trên tường có kính.', 'Open the window, please.', 'Vui lòng mở cửa sổ.', 113),
  (1, 'door', NULL, 'noun', 'A thing you open to enter a room.', 'Cánh cửa, thứ mở ra để vào phòng.', 'Close the door quietly.', 'Hãy đóng cửa nhẹ nhàng.', 114),
  (1, 'room', NULL, 'noun', 'A part of a building with walls.', 'Căn phòng, một phần của tòa nhà có tường.', 'This room is clean.', 'Căn phòng này sạch sẽ.', 115),
  (1, 'house', NULL, 'noun', 'A building where people live.', 'Ngôi nhà, nơi con người sinh sống.', 'Their house is small but bright.', 'Nhà của họ nhỏ nhưng sáng.', 116),
  (1, 'street', NULL, 'noun', 'A road in a town or city.', 'Đường phố trong thị trấn hoặc thành phố.', 'The street is busy today.', 'Con đường hôm nay rất đông.', 117),
  (1, 'school', NULL, 'noun', 'A place where students learn.', 'Trường học, nơi học sinh học tập.', 'Our school starts at seven.', 'Trường của chúng tôi bắt đầu lúc bảy giờ.', 118),
  (1, 'class', NULL, 'noun', 'A lesson or group of students.', 'Lớp học hoặc buổi học.', 'English class is fun today.', 'Lớp tiếng Anh hôm nay vui.', 119),
  (1, 'pen', NULL, 'noun', 'A tool used for writing with ink.', 'Cây bút mực, dụng cụ để viết.', 'I need a blue pen.', 'Tôi cần một cây bút màu xanh.', 120),
  (1, 'pencil', NULL, 'noun', 'A tool used for writing or drawing.', 'Bút chì, dụng cụ để viết hoặc vẽ.', 'Use a pencil for this exercise.', 'Hãy dùng bút chì cho bài tập này.', 121),
  (1, 'bag', NULL, 'noun', 'A container used for carrying things.', 'Cái túi, vật dùng để mang đồ.', 'Her bag is on the chair.', 'Túi của cô ấy ở trên ghế.', 122),
  (1, 'phone', NULL, 'noun', 'A device used to call or message people.', 'Điện thoại, thiết bị để gọi hoặc nhắn tin.', 'My phone is in my bag.', 'Điện thoại của tôi ở trong túi.', 123),
  (1, 'friend', NULL, 'noun', 'A person you like and know well.', 'Bạn bè, người bạn thích và quen thân.', 'My friend helps me study.', 'Bạn tôi giúp tôi học.', 124),
  (1, 'family', NULL, 'noun', 'A group of related people.', 'Gia đình, nhóm người có quan hệ thân thuộc.', 'My family eats dinner together.', 'Gia đình tôi ăn tối cùng nhau.', 125),
  (1, 'mother', NULL, 'noun', 'A female parent.', 'Mẹ, người sinh hoặc nuôi dưỡng con.', 'My mother cooks rice.', 'Mẹ tôi nấu cơm.', 126),
  (1, 'father', NULL, 'noun', 'A male parent.', 'Cha hoặc bố, người sinh hoặc nuôi dưỡng con.', 'His father works at home.', 'Bố anh ấy làm việc ở nhà.', 127),
  (1, 'sister', NULL, 'noun', 'A female sibling.', 'Chị hoặc em gái.', 'My sister reads a book.', 'Chị tôi đọc một cuốn sách.', 128),
  (1, 'brother', NULL, 'noun', 'A male sibling.', 'Anh hoặc em trai.', 'Her brother plays football.', 'Em trai cô ấy chơi bóng đá.', 129),
  (1, 'morning', NULL, 'noun', 'The early part of the day.', 'Buổi sáng, phần đầu của ngày.', 'I study in the morning.', 'Tôi học vào buổi sáng.', 130),
  (1, 'evening', NULL, 'noun', 'The part of the day after afternoon.', 'Buổi tối, thời gian sau buổi chiều.', 'We walk in the evening.', 'Chúng tôi đi bộ vào buổi tối.', 131),
  (1, 'night', NULL, 'noun', 'The dark part of the day.', 'Ban đêm, phần tối của ngày.', 'The city is quiet at night.', 'Thành phố yên tĩnh vào ban đêm.', 132),
  (1, 'today', NULL, 'adverb', 'On this day.', 'Hôm nay, trong ngày này.', 'Today is a good day.', 'Hôm nay là một ngày tốt.', 133),
  (1, 'tomorrow', NULL, 'adverb', 'On the day after today.', 'Ngày mai, ngày sau hôm nay.', 'We have a test tomorrow.', 'Ngày mai chúng tôi có bài kiểm tra.', 134),
  (1, 'happy', NULL, 'adjective', 'Feeling good or pleased.', 'Vui vẻ, cảm thấy tốt hoặc hài lòng.', 'She is happy with her score.', 'Cô ấy vui với điểm số của mình.', 135),
  (1, 'tired', NULL, 'adjective', 'Needing rest or sleep.', 'Mệt mỏi, cần nghỉ ngơi hoặc ngủ.', 'I am tired after school.', 'Tôi mệt sau giờ học.', 136),
  (1, 'hungry', NULL, 'adjective', 'Wanting food.', 'Đói, muốn ăn.', 'The children are hungry.', 'Bọn trẻ đang đói.', 137),
  (1, 'thirsty', NULL, 'adjective', 'Wanting a drink.', 'Khát, muốn uống nước.', 'He is thirsty after running.', 'Anh ấy khát sau khi chạy.', 138),
  (1, 'clean', NULL, 'adjective', 'Not dirty.', 'Sạch, không bẩn.', 'The kitchen is clean.', 'Nhà bếp sạch sẽ.', 139),
  (1, 'dirty', NULL, 'adjective', 'Not clean.', 'Bẩn, không sạch.', 'Your shoes are dirty.', 'Giày của bạn bị bẩn.', 140),
  (1, 'open', NULL, 'verb', 'To move something so people can enter or use it.', 'Mở, làm cho có thể vào hoặc sử dụng.', 'Open your book to page ten.', 'Mở sách đến trang mười.', 141),
  (1, 'close', NULL, 'verb', 'To shut something.', 'Đóng, làm cho khép lại.', 'Close your notebook now.', 'Bây giờ hãy đóng vở lại.', 142),
  (1, 'buy', NULL, 'verb', 'To get something by paying money.', 'Mua, nhận thứ gì bằng cách trả tiền.', 'I buy fruit at the market.', 'Tôi mua trái cây ở chợ.', 143),
  (1, 'sell', NULL, 'verb', 'To give something for money.', 'Bán, đưa thứ gì để nhận tiền.', 'They sell bread near school.', 'Họ bán bánh mì gần trường.', 144),
  (1, 'read', NULL, 'verb', 'To look at words and understand them.', 'Đọc, nhìn chữ và hiểu nội dung.', 'Read the sentence again.', 'Hãy đọc lại câu đó.', 145),
  (1, 'write', NULL, 'verb', 'To make words with a pen or keyboard.', 'Viết, tạo chữ bằng bút hoặc bàn phím.', 'Write your name here.', 'Viết tên của bạn ở đây.', 146),
  (1, 'speak', NULL, 'verb', 'To say words.', 'Nói, phát ra lời.', 'Please speak slowly.', 'Vui lòng nói chậm.', 147),
  (1, 'walk', NULL, 'verb', 'To move on foot.', 'Đi bộ, di chuyển bằng chân.', 'We walk to school.', 'Chúng tôi đi bộ đến trường.', 148),
  (1, 'wait', NULL, 'verb', 'To stay until something happens.', 'Chờ đợi cho đến khi điều gì xảy ra.', 'Wait for me at the door.', 'Hãy chờ tôi ở cửa.', 149),
  (1, 'help', NULL, 'verb', 'To make something easier for someone.', 'Giúp đỡ, làm việc gì dễ hơn cho ai đó.', 'Can you help me?', 'Bạn có thể giúp tôi không?', 150),

  (2, 'airport', NULL, 'noun', 'A place where planes arrive and leave.', 'Sân bay, nơi máy bay đến và đi.', 'We arrived at the airport early.', 'Chúng tôi đến sân bay sớm.', 101),
  (2, 'passport', NULL, 'noun', 'An official document used for travel.', 'Hộ chiếu, giấy tờ chính thức để đi lại quốc tế.', 'Keep your passport in your bag.', 'Hãy giữ hộ chiếu trong túi.', 102),
  (2, 'boarding pass', NULL, 'noun', 'A document that lets you get on a plane.', 'Thẻ lên máy bay.', 'Show your boarding pass at the gate.', 'Xuất trình thẻ lên máy bay ở cổng.', 103),
  (2, 'gate', NULL, 'noun', 'The place where passengers board a plane.', 'Cổng lên máy bay.', 'Our gate is number twelve.', 'Cổng của chúng tôi là số mười hai.', 104),
  (2, 'seat', NULL, 'noun', 'A place where you sit.', 'Chỗ ngồi.', 'My seat is near the window.', 'Chỗ ngồi của tôi gần cửa sổ.', 105),
  (2, 'aisle', NULL, 'noun', 'A passage between rows of seats.', 'Lối đi giữa các hàng ghế.', 'The flight attendant walks down the aisle.', 'Tiếp viên đi dọc lối đi.', 106),
  (2, 'window seat', NULL, 'noun', 'A seat next to a window.', 'Ghế cạnh cửa sổ.', 'She prefers a window seat.', 'Cô ấy thích ghế cạnh cửa sổ.', 107),
  (2, 'baggage claim', NULL, 'noun', 'The place where travelers collect bags.', 'Khu nhận hành lý.', 'Meet me at baggage claim.', 'Gặp tôi ở khu nhận hành lý.', 108),
  (2, 'customs', NULL, 'noun', 'The place where bags and goods are checked.', 'Hải quan, nơi kiểm tra hành lý và hàng hóa.', 'We passed through customs quickly.', 'Chúng tôi qua hải quan nhanh chóng.', 109),
  (2, 'visa', NULL, 'noun', 'Permission to enter a country.', 'Thị thực, giấy phép nhập cảnh.', 'Do you need a visa for this trip?', 'Bạn có cần thị thực cho chuyến đi này không?', 110),
  (2, 'map', NULL, 'noun', 'A drawing that shows places and roads.', 'Bản đồ, hình vẽ chỉ địa điểm và đường đi.', 'Use the map to find the hotel.', 'Dùng bản đồ để tìm khách sạn.', 111),
  (2, 'guidebook', NULL, 'noun', 'A book with travel information.', 'Sách hướng dẫn du lịch.', 'This guidebook lists good restaurants.', 'Sách hướng dẫn này liệt kê các nhà hàng tốt.', 112),
  (2, 'taxi', NULL, 'noun', 'A car with a driver that you pay to ride in.', 'Taxi, xe có tài xế mà bạn trả tiền để đi.', 'Take a taxi to the hotel.', 'Hãy đi taxi đến khách sạn.', 113),
  (2, 'bus stop', NULL, 'noun', 'A place where buses pick up passengers.', 'Trạm xe buýt.', 'The bus stop is across the street.', 'Trạm xe buýt ở bên kia đường.', 114),
  (2, 'train station', NULL, 'noun', 'A place where trains arrive and leave.', 'Ga tàu.', 'The train station is crowded.', 'Ga tàu rất đông.', 115),
  (2, 'platform', NULL, 'noun', 'The area where passengers wait for a train.', 'Sân ga, nơi hành khách chờ tàu.', 'The train leaves from platform three.', 'Tàu rời đi từ sân ga số ba.', 116),
  (2, 'subway', NULL, 'noun', 'An underground train system.', 'Tàu điện ngầm.', 'We took the subway downtown.', 'Chúng tôi đi tàu điện ngầm vào trung tâm.', 117),
  (2, 'hotel', NULL, 'noun', 'A place where travelers pay to sleep.', 'Khách sạn.', 'The hotel has a nice view.', 'Khách sạn có tầm nhìn đẹp.', 118),
  (2, 'hostel', NULL, 'noun', 'A cheap place for travelers to stay.', 'Nhà nghỉ giá rẻ cho khách du lịch.', 'The hostel is close to the station.', 'Nhà nghỉ gần ga tàu.', 119),
  (2, 'room key', NULL, 'noun', 'A key or card for a hotel room.', 'Chìa khóa hoặc thẻ phòng khách sạn.', 'Do not lose your room key.', 'Đừng làm mất thẻ phòng.', 120),
  (2, 'reception', NULL, 'noun', 'The hotel desk where guests get help.', 'Quầy lễ tân khách sạn.', 'Ask reception for a towel.', 'Hỏi lễ tân để lấy khăn.', 121),
  (2, 'check in', NULL, 'verb', 'To register when you arrive at a hotel or airport.', 'Làm thủ tục khi đến khách sạn hoặc sân bay.', 'We check in at two o clock.', 'Chúng tôi làm thủ tục lúc hai giờ.', 122),
  (2, 'check out', NULL, 'verb', 'To leave a hotel after paying.', 'Trả phòng sau khi thanh toán.', 'We check out before noon.', 'Chúng tôi trả phòng trước buổi trưa.', 123),
  (2, 'elevator', NULL, 'noun', 'A machine that carries people between floors.', 'Thang máy.', 'Take the elevator to the fifth floor.', 'Đi thang máy lên tầng năm.', 124),
  (2, 'reservation code', NULL, 'noun', 'A number or code for a booking.', 'Mã đặt chỗ.', 'Please enter your reservation code.', 'Vui lòng nhập mã đặt chỗ.', 125),
  (2, 'tour', NULL, 'noun', 'A planned visit to places.', 'Chuyến tham quan có kế hoạch.', 'The city tour starts at nine.', 'Chuyến tham quan thành phố bắt đầu lúc chín giờ.', 126),
  (2, 'museum', NULL, 'noun', 'A place with objects of art, history, or science.', 'Bảo tàng.', 'We visited a history museum.', 'Chúng tôi đã thăm một bảo tàng lịch sử.', 127),
  (2, 'beach', NULL, 'noun', 'Land beside the sea with sand or stones.', 'Bãi biển.', 'The beach is beautiful at sunset.', 'Bãi biển đẹp lúc hoàng hôn.', 128),
  (2, 'mountain', NULL, 'noun', 'A very high hill.', 'Ngọn núi.', 'They climbed a mountain last summer.', 'Họ leo núi vào mùa hè năm ngoái.', 129),
  (2, 'island', NULL, 'noun', 'Land surrounded by water.', 'Hòn đảo.', 'The island is quiet and green.', 'Hòn đảo yên tĩnh và xanh.', 130),
  (2, 'restaurant', NULL, 'noun', 'A place where people buy and eat meals.', 'Nhà hàng.', 'This restaurant serves local food.', 'Nhà hàng này phục vụ món địa phương.', 131),
  (2, 'menu', NULL, 'noun', 'A list of food and drinks.', 'Thực đơn.', 'Can I see the menu?', 'Tôi có thể xem thực đơn không?', 132),
  (2, 'bill', NULL, 'noun', 'A note showing how much you must pay.', 'Hóa đơn cần thanh toán.', 'Please bring us the bill.', 'Vui lòng mang hóa đơn cho chúng tôi.', 133),
  (2, 'currency', NULL, 'noun', 'The money used in a country.', 'Đơn vị tiền tệ của một quốc gia.', 'What currency do they use here?', 'Ở đây họ dùng tiền tệ gì?', 134),
  (2, 'exchange', NULL, 'verb', 'To change money from one currency to another.', 'Đổi tiền từ loại tiền này sang loại khác.', 'I need to exchange dollars.', 'Tôi cần đổi đô la.', 135),
  (2, 'receipt', NULL, 'noun', 'A paper or message that shows payment.', 'Biên lai hoặc hóa đơn xác nhận thanh toán.', 'Keep the receipt for your bag.', 'Giữ biên lai cho túi của bạn.', 136),
  (2, 'souvenir', NULL, 'noun', 'A thing bought to remember a place.', 'Quà lưu niệm.', 'She bought a small souvenir.', 'Cô ấy mua một món quà lưu niệm nhỏ.', 137),
  (2, 'destination', NULL, 'noun', 'The place where someone is going.', 'Điểm đến.', 'Paris is our final destination.', 'Paris là điểm đến cuối cùng của chúng tôi.', 138),
  (2, 'itinerary', NULL, 'noun', 'A travel plan with times and places.', 'Lịch trình du lịch.', 'The itinerary includes three cities.', 'Lịch trình gồm ba thành phố.', 139),
  (2, 'delay', NULL, 'noun', 'A time when something happens later than planned.', 'Sự chậm trễ.', 'There is a delay because of rain.', 'Có sự chậm trễ vì mưa.', 140),
  (2, 'cancel', NULL, 'verb', 'To stop a plan or booking.', 'Hủy kế hoạch hoặc đặt chỗ.', 'They had to cancel the flight.', 'Họ phải hủy chuyến bay.', 141),
  (2, 'arrival', NULL, 'noun', 'The act or time of reaching a place.', 'Sự đến nơi hoặc thời điểm đến.', 'Our arrival time is 6 p.m.', 'Giờ đến của chúng tôi là 6 giờ tối.', 142),
  (2, 'suitcase', NULL, 'noun', 'A case used for clothes when traveling.', 'Va li dùng để đựng quần áo khi đi du lịch.', 'My suitcase is too heavy.', 'Va li của tôi quá nặng.', 143),
  (2, 'backpack', NULL, 'noun', 'A bag carried on the back.', 'Ba lô đeo sau lưng.', 'He carries a small backpack.', 'Anh ấy mang một chiếc ba lô nhỏ.', 144),
  (2, 'carry on', NULL, 'noun', 'A small bag taken onto a plane.', 'Hành lý xách tay lên máy bay.', 'Your carry on goes above the seat.', 'Hành lý xách tay của bạn để phía trên ghế.', 145),
  (2, 'sunscreen', NULL, 'noun', 'Cream that protects skin from the sun.', 'Kem chống nắng.', 'Use sunscreen at the beach.', 'Hãy dùng kem chống nắng ở bãi biển.', 146),
  (2, 'charger', NULL, 'noun', 'A device used to charge a phone or battery.', 'Bộ sạc điện thoại hoặc pin.', 'I forgot my phone charger.', 'Tôi quên bộ sạc điện thoại.', 147),
  (2, 'adapter', NULL, 'noun', 'A device that helps plugs fit sockets.', 'Bộ chuyển đổi phích cắm.', 'You need an adapter in this country.', 'Bạn cần bộ chuyển đổi ở quốc gia này.', 148),
  (2, 'landmark', NULL, 'noun', 'A famous or easy to recognize place.', 'Địa danh nổi tiếng hoặc dễ nhận ra.', 'The tower is a famous landmark.', 'Tòa tháp là một địa danh nổi tiếng.', 149),
  (2, 'direction', NULL, 'noun', 'Information about how to get somewhere.', 'Chỉ dẫn đường đi.', 'Ask for direction at the station.', 'Hỏi đường ở ga tàu.', 150),

  (3, 'agenda', NULL, 'noun', 'A list of topics for a meeting.', 'Chương trình nghị sự, danh sách nội dung họp.', 'The agenda has five items.', 'Chương trình họp có năm mục.', 101),
  (3, 'client', NULL, 'noun', 'A person or company that uses a service.', 'Khách hàng sử dụng dịch vụ.', 'The client asked for a new report.', 'Khách hàng yêu cầu một báo cáo mới.', 102),
  (3, 'customer', NULL, 'noun', 'A person who buys goods or services.', 'Khách hàng mua hàng hóa hoặc dịch vụ.', 'The customer needs help.', 'Khách hàng cần giúp đỡ.', 103),
  (3, 'invoice', NULL, 'noun', 'A document asking for payment.', 'Hóa đơn yêu cầu thanh toán.', 'Please send the invoice today.', 'Vui lòng gửi hóa đơn hôm nay.', 104),
  (3, 'budget', NULL, 'noun', 'A plan for spending money.', 'Ngân sách, kế hoạch chi tiêu tiền.', 'The project has a small budget.', 'Dự án có ngân sách nhỏ.', 105),
  (3, 'revenue', NULL, 'noun', 'Money that a business receives.', 'Doanh thu mà doanh nghiệp nhận được.', 'Revenue increased this month.', 'Doanh thu tăng trong tháng này.', 106),
  (3, 'expense', NULL, 'noun', 'Money spent on something.', 'Chi phí, số tiền đã chi.', 'Travel is a major expense.', 'Đi lại là một chi phí lớn.', 107),
  (3, 'profit', NULL, 'noun', 'Money earned after costs are paid.', 'Lợi nhuận sau khi trừ chi phí.', 'The company made a profit.', 'Công ty đã có lợi nhuận.', 108),
  (3, 'target', NULL, 'noun', 'A goal that someone tries to reach.', 'Mục tiêu cần đạt.', 'Our sales target is clear.', 'Mục tiêu bán hàng của chúng tôi rõ ràng.', 109),
  (3, 'strategy', NULL, 'noun', 'A plan for reaching a goal.', 'Chiến lược để đạt mục tiêu.', 'We need a better strategy.', 'Chúng ta cần một chiến lược tốt hơn.', 110),
  (3, 'project', NULL, 'noun', 'A planned piece of work.', 'Dự án, công việc có kế hoạch.', 'This project ends in June.', 'Dự án này kết thúc vào tháng Sáu.', 111),
  (3, 'task', NULL, 'noun', 'A piece of work to do.', 'Nhiệm vụ hoặc việc cần làm.', 'Finish this task before lunch.', 'Hoàn thành nhiệm vụ này trước bữa trưa.', 112),
  (3, 'update', NULL, 'noun', 'New information about progress.', 'Cập nhật thông tin mới về tiến độ.', 'Give me an update tomorrow.', 'Hãy cập nhật cho tôi vào ngày mai.', 113),
  (3, 'report', NULL, 'noun', 'A document with information or results.', 'Báo cáo chứa thông tin hoặc kết quả.', 'The report is ready.', 'Báo cáo đã sẵn sàng.', 114),
  (3, 'presentation', NULL, 'noun', 'A talk that explains ideas to people.', 'Bài thuyết trình giải thích ý tưởng.', 'Her presentation was clear.', 'Bài thuyết trình của cô ấy rõ ràng.', 115),
  (3, 'proposal', NULL, 'noun', 'A suggested plan.', 'Đề xuất hoặc kế hoạch được gợi ý.', 'The proposal needs more detail.', 'Đề xuất cần thêm chi tiết.', 116),
  (3, 'contract', NULL, 'noun', 'A legal agreement.', 'Hợp đồng, thỏa thuận pháp lý.', 'They signed the contract.', 'Họ đã ký hợp đồng.', 117),
  (3, 'signature', NULL, 'noun', 'A written name used to approve something.', 'Chữ ký dùng để xác nhận.', 'Your signature is required.', 'Cần chữ ký của bạn.', 118),
  (3, 'department', NULL, 'noun', 'A part of a company with a specific job.', 'Phòng ban trong công ty.', 'She works in the finance department.', 'Cô ấy làm ở phòng tài chính.', 119),
  (3, 'manager', NULL, 'noun', 'A person who leads a team or department.', 'Quản lý, người dẫn dắt nhóm hoặc phòng ban.', 'The manager approved the plan.', 'Quản lý đã duyệt kế hoạch.', 120),
  (3, 'colleague', NULL, 'noun', 'A person you work with.', 'Đồng nghiệp, người làm việc cùng.', 'My colleague joined the call.', 'Đồng nghiệp của tôi tham gia cuộc gọi.', 121),
  (3, 'teamwork', NULL, 'noun', 'Work done together by a group.', 'Làm việc nhóm.', 'Good teamwork saves time.', 'Làm việc nhóm tốt giúp tiết kiệm thời gian.', 122),
  (3, 'leadership', NULL, 'noun', 'The ability to guide people.', 'Khả năng lãnh đạo con người.', 'Leadership is important in this role.', 'Lãnh đạo rất quan trọng trong vai trò này.', 123),
  (3, 'priority', NULL, 'noun', 'Something more important than other things.', 'Ưu tiên, điều quan trọng hơn các việc khác.', 'Safety is our first priority.', 'An toàn là ưu tiên đầu tiên của chúng tôi.', 124),
  (3, 'milestone', NULL, 'noun', 'An important point in a project.', 'Cột mốc quan trọng trong dự án.', 'We reached a key milestone.', 'Chúng tôi đã đạt một cột mốc quan trọng.', 125),
  (3, 'timeline', NULL, 'noun', 'A plan showing when things happen.', 'Dòng thời gian hoặc lịch tiến độ.', 'The timeline is too short.', 'Tiến độ này quá ngắn.', 126),
  (3, 'risk', NULL, 'noun', 'The possibility of a problem or loss.', 'Rủi ro, khả năng có vấn đề hoặc mất mát.', 'The team discussed the main risk.', 'Nhóm đã thảo luận rủi ro chính.', 127),
  (3, 'issue', NULL, 'noun', 'A problem that needs attention.', 'Vấn đề cần được xử lý.', 'There is an issue with the file.', 'Có vấn đề với tệp này.', 128),
  (3, 'solution', NULL, 'noun', 'An answer to a problem.', 'Giải pháp cho một vấn đề.', 'We found a simple solution.', 'Chúng tôi tìm thấy một giải pháp đơn giản.', 129),
  (3, 'decision', NULL, 'noun', 'A choice made after thinking.', 'Quyết định sau khi suy nghĩ.', 'The decision was made yesterday.', 'Quyết định đã được đưa ra hôm qua.', 130),
  (3, 'approval', NULL, 'noun', 'Permission to do something.', 'Sự phê duyệt hoặc cho phép.', 'We need approval from finance.', 'Chúng tôi cần phê duyệt từ phòng tài chính.', 131),
  (3, 'negotiation', NULL, 'noun', 'Discussion to reach an agreement.', 'Đàm phán để đạt thỏa thuận.', 'The negotiation lasted two hours.', 'Cuộc đàm phán kéo dài hai giờ.', 132),
  (3, 'supplier', NULL, 'noun', 'A company that provides goods or services.', 'Nhà cung cấp hàng hóa hoặc dịch vụ.', 'The supplier sent the materials.', 'Nhà cung cấp đã gửi vật liệu.', 133),
  (3, 'inventory', NULL, 'noun', 'Goods that a business keeps for sale or use.', 'Hàng tồn kho hoặc danh mục hàng hóa.', 'Inventory is checked every week.', 'Hàng tồn kho được kiểm tra mỗi tuần.', 134),
  (3, 'shipment', NULL, 'noun', 'Goods sent from one place to another.', 'Lô hàng được gửi đi.', 'The shipment arrived late.', 'Lô hàng đến muộn.', 135),
  (3, 'warehouse', NULL, 'noun', 'A large building for storing goods.', 'Kho hàng lớn để lưu trữ hàng hóa.', 'The boxes are in the warehouse.', 'Các hộp ở trong kho.', 136),
  (3, 'quality', NULL, 'noun', 'How good something is.', 'Chất lượng của một thứ.', 'Quality matters more than speed.', 'Chất lượng quan trọng hơn tốc độ.', 137),
  (3, 'productivity', NULL, 'noun', 'The rate of useful work done.', 'Năng suất, mức độ hoàn thành công việc hữu ích.', 'Productivity improved after training.', 'Năng suất cải thiện sau đào tạo.', 138),
  (3, 'performance', NULL, 'noun', 'How well someone or something works.', 'Hiệu suất hoặc kết quả làm việc.', 'Her performance was excellent.', 'Hiệu suất của cô ấy rất xuất sắc.', 139),
  (3, 'training', NULL, 'noun', 'Practice or lessons for a job.', 'Đào tạo hoặc huấn luyện cho công việc.', 'New staff need training.', 'Nhân viên mới cần đào tạo.', 140),
  (3, 'onboarding', NULL, 'noun', 'The process of welcoming and training new staff.', 'Quy trình tiếp nhận và đào tạo nhân viên mới.', 'Onboarding starts on Monday.', 'Quy trình onboarding bắt đầu vào thứ Hai.', 141),
  (3, 'interview', NULL, 'noun', 'A meeting to decide if someone gets a job.', 'Buổi phỏng vấn xin việc.', 'The interview lasted thirty minutes.', 'Buổi phỏng vấn kéo dài ba mươi phút.', 142),
  (3, 'resume', NULL, 'noun', 'A document that lists work and education.', 'Sơ yếu lý lịch hoặc CV.', 'Attach your resume to the email.', 'Đính kèm CV của bạn vào email.', 143),
  (3, 'salary', NULL, 'noun', 'Money paid regularly for work.', 'Lương được trả định kỳ cho công việc.', 'The salary is paid monthly.', 'Lương được trả hàng tháng.', 144),
  (3, 'policy', NULL, 'noun', 'A rule or plan used by an organization.', 'Chính sách hoặc quy định của tổ chức.', 'Read the company policy.', 'Hãy đọc chính sách công ty.', 145),
  (3, 'workflow', NULL, 'noun', 'The order of steps in work.', 'Quy trình làm việc theo các bước.', 'This workflow is easy to follow.', 'Quy trình này dễ làm theo.', 146),
  (3, 'spreadsheet', NULL, 'noun', 'A file with rows and columns for data.', 'Bảng tính gồm hàng và cột dữ liệu.', 'Update the spreadsheet today.', 'Hãy cập nhật bảng tính hôm nay.', 147),
  (3, 'forecast', NULL, 'noun', 'A prediction about the future.', 'Dự báo về tương lai.', 'The sales forecast looks positive.', 'Dự báo bán hàng có vẻ tích cực.', 148),
  (3, 'market', NULL, 'noun', 'The group of buyers for a product.', 'Thị trường, nhóm người mua sản phẩm.', 'The market is growing fast.', 'Thị trường đang phát triển nhanh.', 149),
  (3, 'campaign', NULL, 'noun', 'A planned set of actions to reach a goal.', 'Chiến dịch gồm các hoạt động có kế hoạch.', 'The campaign starts next week.', 'Chiến dịch bắt đầu tuần tới.', 150);
